"""Add Guardian model

Revision ID: 209f8287b6d8
Revises: 71228805b2b1
Create Date: 2026-02-03 14:31:08.273529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '209f8287b6d8'
down_revision: Union[str, Sequence[str], None] = '71228805b2b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guardians', sa.Column('ward_id', sa.UUID(), nullable=False))
    op.add_column('guardians', sa.Column('guardian_id', sa.UUID(), nullable=False))
    op.add_column('guardians', sa.Column('alias', sa.String(), nullable=True))
    op.add_column('guardians', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.create_index(op.f('ix_guardians_guardian_id'), 'guardians', ['guardian_id'], unique=False)
    op.create_index(op.f('ix_guardians_ward_id'), 'guardians', ['ward_id'], unique=False)
    op.drop_constraint(op.f('guardians_user_id_fkey'), 'guardians', type_='foreignkey')
    op.create_foreign_key(None, 'guardians', 'users', ['guardian_id'], ['id'])
    op.create_foreign_key(None, 'guardians', 'users', ['ward_id'], ['id'])
    op.drop_column('guardians', 'relation')
    op.drop_column('guardians', 'notification_config')
    op.drop_column('guardians', 'user_id')
    op.drop_column('guardians', 'phone')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guardians', sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('guardians', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('guardians', sa.Column('notification_config', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('guardians', sa.Column('relation', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'guardians', type_='foreignkey')
    op.drop_constraint(None, 'guardians', type_='foreignkey')
    op.create_foreign_key(op.f('guardians_user_id_fkey'), 'guardians', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_guardians_ward_id'), table_name='guardians')
    op.drop_index(op.f('ix_guardians_guardian_id'), table_name='guardians')
    op.drop_column('guardians', 'created_at')
    op.drop_column('guardians', 'alias')
    op.drop_column('guardians', 'guardian_id')
    op.drop_column('guardians', 'ward_id')
    # ### end Alembic commands ###
