"""Add Guardian Pulse models

Revision ID: 7718e8175c84
Revises: 990c0f877aeb
Create Date: 2026-02-03 13:57:44.355966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7718e8175c84'
down_revision: Union[str, Sequence[str], None] = '990c0f877aeb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_signals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('signal_type', sa.Enum('APP_OPEN', 'APP_FOREGROUND', 'TOUCH_EVENT', 'HEARTBEAT', 'MANUAL_CHECKIN', name='signaltype'), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('device_info', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_signals_timestamp'), 'activity_signals', ['timestamp'], unique=False)
    op.create_index(op.f('ix_activity_signals_user_id'), 'activity_signals', ['user_id'], unique=False)
    op.create_table('monitoring_policies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('threshold_hours', sa.Integer(), nullable=False),
    sa.Column('quiet_start', sa.Time(), nullable=False),
    sa.Column('quiet_end', sa.Time(), nullable=False),
    sa.Column('escalation_enabled', sa.Boolean(), nullable=True),
    sa.Column('escalation_delay_minutes', sa.Integer(), nullable=True),
    sa.Column('sensitivity', sa.Enum('RELAXED', 'NORMAL', 'STRICT', name='sensitivitylevel'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('sms_fallback_enabled', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('pulse_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'RESOLVED', 'DISMISSED', 'EXPIRED', name='pulsestatus'), nullable=False),
    sa.Column('current_stage', sa.Enum('SOFT_CHECK', 'GUARDIAN_ALERT', 'EMERGENCY', name='pulsestage'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('soft_check_sent_at', sa.DateTime(), nullable=True),
    sa.Column('guardian_notified_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_by', sa.UUID(), nullable=True),
    sa.Column('resolution_method', sa.String(), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pulse_events_user_id'), 'pulse_events', ['user_id'], unique=False)
    op.add_column('users', sa.Column('last_active_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_active_at')
    op.drop_index(op.f('ix_pulse_events_user_id'), table_name='pulse_events')
    op.drop_table('pulse_events')
    op.drop_table('monitoring_policies')
    op.drop_index(op.f('ix_activity_signals_user_id'), table_name='activity_signals')
    op.drop_index(op.f('ix_activity_signals_timestamp'), table_name='activity_signals')
    op.drop_table('activity_signals')
    # ### end Alembic commands ###
