"""Add UserConfig and TimerStatus

Revision ID: 7fafa3ba0a2c
Revises: 209f8287b6d8
Create Date: 2026-02-04 01:08:15.588723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fafa3ba0a2c'
down_revision: Union[str, Sequence[str], None] = '209f8287b6d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timer_statuses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('last_check_in', sa.DateTime(), nullable=True),
    sa.Column('deadline_timestamp', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'GRACE', 'EXPIRED', 'STOPPED', name='timerstate'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('user_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('period', sa.Integer(), nullable=False),
    sa.Column('grace_period', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_configs')
    op.drop_table('timer_statuses')
    # ### end Alembic commands ###
